# Adapted from https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_seqtk_1_0_r75/.shed.yml
categories:
- Tool Dependency Packages
description: |
  Contains a tool dependency definition that downloads and compiles version
  0.1.0-r75 of the segtk package.
long_description: |
  Sequence Toolkit is a suite of utilities to work with FastA and FastQ data
  https://github.com/lh3/seqtk
name: package_seqtk_1_0_r75
owner: planemo
remote_repository_url: https://github.com/galaxyproject/planemo/tree/master/project_templates/package_seqtk_1_0_r75
